OBS-Sistemi/OBS-Sistemi.Web/Controllers/OgrElemaniController.cs
using Microsoft.AspNetCore.Mvc;

namespace OBS_Sistemi.Web.Controllers
{
    public class OgrElemaniController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult BolumMufredati()
        {
            return View();
        }
        public IActionResult VerilenDersler() 
        { 
            return View(); 
        }
        public IActionResult DersProgrami()
        {
            return View();
        }
        public IActionResult DersKayitOnayi()
        {
            return View();
        }
        public IActionResult SinavTakvimi()
        {
            return View();
        }
        public IActionResult SinavTanimla()
        {
            return View();
        }
        public IActionResult Degerlendirme()
        {
            return View();
        }
        public IActionResult Danismanlik()
        {
            return View();
        }
        public IActionResult OzlukBilgileri()
        {
            return View();
        }
        public IActionResult Mesajlar()
        {
            return View();
        }

    }
}

OBS-Sistemi/OBS-Sistemi.Web/Controllers/OgrenciController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OBS_Sistemi.Web.Data;
using OBS_Sistemi.Web.Models;
using System.Data.Entity;

namespace OBS_Sistemi.Web.Controllers
{
    public class OgrenciController : Controller
    {
        private readonly MainContext _context;//dependency injection
        

        public OgrenciController()
        {
            _context = new MainContext();
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult OzlukBilgileri(int kullaniciId)
        { 
            
            var joinedData = from user in _context.tb_Kullanicilar
                             join student in _context.tb_Ogrenciler on user.KullaniciID equals student.KullaniciID
                             join department in _context.tb_Bolumler on student.BolumID equals department.BolumID
                             where student.KullaniciID == kullaniciId


                             select new
                             {
                                 UserName = user.KullaniciAdi,
                                 StudentName = student.Adi,
                                 DepartmentName = department.BolumAdi
                                 // Diğer gerekli alanları buraya ekleyebilirsiniz
                             };

            // LINQ sorgusunu çalıştırarak verileri alabiliriz
            var result =joinedData.FirstOrDefault();

            return View();
        }
        public IActionResult BolumMufredati()
        {
            return View();
        }
        public IActionResult DonemDersleri()
        {
            return View();
        }
        public IActionResult DersKayit()
        {
            return View();
        }
        public IActionResult DersProgrami()
        {
            return View();
        }        
        public IActionResult SinavTakvimi()
        {
            return View();
        }
        public IActionResult SinavNotlari()
        {
            return View();
        }

        public IActionResult Transkript()
        {
            return View();
        }
        


    }
}

OBS-Sistemi/OBS-Sistemi.Web/Views/Partials/OgrElemaniYanMenu.cshtml
<div class="sidebar">
    <div class="sidebar-inner">
        <div class="sidebar-logo">
            <div class="d-flex align-items-center flex-nowrap">
                <a class="sidebar-link text-decoration-none" href="#">
                    <div class="d-flex align-items-center flex-nowrap">
                        <div class="logo-sm">
                            <div class="logo d-flex align-items-center justify-content-center">
                                LOGO
                            </div>
                        </div>
                        <div class="logo-text d-flex align-items-center justify-content-center">
                            LOGO
                        </div>
                    </div>
                </a>
                <div class="">
                    <div class="mobile-toggle sidebar-toggle">
                        <a href="#" class="text-decoration-none">
                            <i class="far fa-times-circle"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>

        <ul class="sidebar-menu scrollable position-relative pt-3">

            <!--AnaSayfa Kısmı-->
            <li class="nav-item dropdown">
                <a class="nav-link wave-effect" asp-action="Index" asp-controller="OgrElemani">
                    <span class="icon-holder">
                        <i class="fas fa-home"></i>
                    </span>
                    <span class="title">Anasayfa</span>
                </a>
            </li>

            <!--Ders Menüsü-->
            <li class="nav-item dropdown">
                <a class="nav-link wave-effect" href="#">
                    <span class="icon-holder">
                        <i class="fas fa-folder-open"></i>
                    </span>
                    <span class="title">Ders İşlemleri</span>
                    <span class="arrow">
                        <i class="fas fa-angle-right"></i>
                    </span>
                </a>
                <ul class="dropdown-menu">
                    <li>
                        <a class="sidebar-link" asp-action="BolumMufredati" asp-controller="OgrElemani">Bölüm Müfredatı</a>
                    </li>
                    <li>
                        <a class="sidebar-link" asp-action="VerilenDersler" asp-controller="OgrElemani">Verilen Dersler</a>
                    </li>
                    <li>
                        <a class="sidebar-link" asp-action="DersProgrami" asp-controller="OgrElemani">Ders Programı</a>
                    </li>
                    <li>
                        <a class="sidebar-link" asp-action="DersKayitOnayi" asp-controller="OgrElemani">Ders Kayıt Onayı</a>
                    </li>
                </ul>
            </li>

            <!--Sınav Menüsü-->
            <li class="nav-item dropdown">
                <a class="nav-link wave-effect dropdown-toggle" href="#">
                    <span class="icon-holder">
                        <i class="fas fa-fingerprint"></i>
                    </span>
                    <span class="title">Sınav İşlemleri</span>
                    <span class="arrow">
                        <i class="fas fa-angle-right"></i>
                    </span>
                </a>
                <ul class="dropdown-menu">
                    <li>
                        <a class="sidebar-link" asp-action="SinavTakvimi" asp-controller="OgrElemani">Sınav Takvimi</a>
                    </li>
                    <li>
                        <a class="sidebar-link" asp-action="SinavTanimla" asp-controller="OgrElemani">Sınav Tanımla</a>
                    </li>
                    <li>
                        <a class="sidebar-link" asp-action="Degerlendirme" asp-controller="OgrElemani">Değerlendirme</a>
                    </li>
                </ul>
            </li>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#">
                    <span class="icon-holder">
                        <i class="fas fa-folder-open"></i>
                    </span>
                    <span class="title">Diğer İşlemler</span>
                    <span class="arrow">
                        <i class="fas fa-angle-right"></i>
                    </span>
                </a>
                <ul class="dropdown-menu">
                    <li>
                        <a class="sidebar-link" asp-action="Danismanlik" asp-controller="OgrElemani">Danışmalık</a>
                    </li>
                    <li>
                        <a class="sidebar-link" asp-action="OzlukBilgileri" asp-controller="OgrElemani">Özlük Bilgileri</a>
                    </li>
                    <li>
                        <a class="sidebar-link" asp-action="Mesajlar" asp-controller="OgrElemani">Mesajlar</a>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
</div>
<div class="container-wide">
    <nav class="navbar navbar-expand navbar-light bg-light">
        <ul class="navbar-nav me-auto">
            <li class="nav-item active">
                <a id="sidebar-toggle" class="sidebar-toggle nav-link" href="#">
                    <i class="fas fa-bars"></i>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Abdullah Elen</a>
            </li>
        </ul>
        <ul class="navbar-nav ms-auto">
            <li class="nav-item">
                <a class="nav-link" href="#">|</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-action="Index" asp-controller="Anasayfa">Oturumu Kapat</a>
            </li>
        </ul>
    </nav>
    

OBS-Sistemi/OBS-Sistemi.Web/Views/Partials/OgrenciYanMenu.cshtml
<div class="sidebar">
    <div class="sidebar-inner">
        <div class="sidebar-logo">
            <div class="d-flex align-items-center flex-nowrap">
                <a class="sidebar-link text-decoration-none" href="#">
                    <div class="d-flex align-items-center flex-nowrap">
                        <div class="logo-sm">
                            <div class="logo d-flex align-items-center justify-content-center">
                                LOGO
                            </div>
                        </div>
                        <div class="logo-text d-flex align-items-center justify-content-center">
                            LOGO
                        </div>
                    </div>
                </a>
                <div class="">
                    <div class="mobile-toggle sidebar-toggle">
                        <a href="#" class="text-decoration-none">
                            <i class="far fa-times-circle"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>

        <ul class="sidebar-menu scrollable position-relative pt-3">

            <li class="nav-item dropdown">
                <a class="nav-link wave-effect" asp-action="Index" asp-controller="Ogrenci">
                    <span class="icon-holder">
                        <i class="fas fa-home"></i>
                    </span>
                    <span class="title">Anasayfa</span>
                </a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link wave-effect" href="#">
                    <span class="icon-holder">
                        <i class="fas fa-folder-open"></i>
                    </span>
                    <span class="title">Ders İşlemleri</span>
                    <span class="arrow">
                        <i class="fas fa-angle-right"></i>
                    </span>
                </a>
                <ul class="dropdown-menu">
                    <li>
                        <a class="sidebar-link" asp-action="BolumMufredati" asp-controller="Ogrenci">Bölüm Müfredatı</a>
                    </li>
                    <li>
                        <a class="sidebar-link" asp-action="DonemDersleri" asp-controller="Ogrenci">Dönem Dersleri</a>
                    </li>
                    <li>
                        <a class="sidebar-link" asp-action="DersProgrami" asp-controller="Ogrenci">Ders Programı</a>
                    </li>
                    <li>
                        <a class="sidebar-link" asp-action="DersKayit" asp-controller="Ogrenci">Ders Kayıt</a>
                    </li>
                </ul>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link wave-effect dropdown-toggle" href="#">
                    <span class="icon-holder">
                        <i class="fas fa-fingerprint"></i>
                    </span>
                    <span class="title">Sınav İşlemleri</span>
                    <span class="arrow">
                        <i class="fas fa-angle-right"></i>
                    </span>
                </a>
                <ul class="dropdown-menu">
                    <li>
                        <a class="sidebar-link" asp-action="SinavTakvimi" asp-controller="Ogrenci">Sınav Takvimi</a>
                    </li>
                    <li>
                        <a class="sidebar-link" asp-action="SinavNotlari" asp-controller="Ogrenci">Sınav Notları</a>
                    </li>
                </ul>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#">
                    <span class="icon-holder">
                        <i class="fas fa-folder-plus"></i>
                    </span>
                    <span class="title">Belgeler</span>
                    <span class="arrow">
                        <i class="fas fa-angle-right"></i>
                    </span>
                </a>
                <ul class="dropdown-menu">
                    <li>
                        <a class="sidebar-link" asp-action="Transkript" asp-controller="Ogrenci">Transkript</a>
                    </li>
                </ul>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#">
                    <span class="icon-holder">
                        <i class="fas fa-folder-open"></i>
                    </span>
                    <span class="title">Diğer İşlemler</span>
                    <span class="arrow">
                        <i class="fas fa-angle-right"></i>
                    </span>
                </a>
                <ul class="dropdown-menu">
                    <li>
                        <a class="sidebar-link" asp-action="OzlukBilgileri" asp-controller="Ogrenci">Özlük Bilgileri</a>
                    </li>
                    
                </ul>
            </li>
        </ul>
    </div>
</div>
<div class="container-wide">
    <nav class="navbar navbar-expand navbar-light bg-light">
        <ul class="navbar-nav me-auto">
            <li class="nav-item active">
                <a id="sidebar-toggle" class="sidebar-toggle nav-link" href="#">
                    <i class="fas fa-bars"></i>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Burak Gündoğan</a>
            </li>
        </ul>
        <ul class="navbar-nav ms-auto">
            <li class="nav-item">
                <a class="nav-link" href="#">|</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-action="Index" asp-controller="Anasayfa">Oturumu Kapat</a>
            </li>
        </ul>
    </nav>
    <div class="container mt-5">
    </div>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="~/js/perfect-scrollbar.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
    <script src="~/js/next-sidebar.js"></script>